export const IndividualDays = [
  'MyMonActions',
  'MyTueActions',
  'MyWedActions',
  'MyThurActions',
  'MyFriActions',
  'MySatActions',
  'MySunActions',
];

export const AllDays = [
  'AvgMonActions',
  'AvgTueActions',
  'AvgWedActions',
  'AvgThurActions',
  'AvgFriActions',
  'AvgSatActions',
  'AvgSunActions',
];

export const MyMonth = [
  'My1Actions',
  'My2Actions',
  'My3Actions',
  'My4Actions',
  'My5Actions',
  'My6Actions',
  'My7Actions',
  'My8Actions',
  'My9Actions',
  'My10Actions',
  'My11Actions',
  'My12Actions',
  'My13Actions',
  'My14Actions',
  'My15Actions',
  'My16Actions',
  'My17Actions',
  'My18Actions',
  'My19Actions',
  'My20Actions',
  'My21Actions',
  'My22Actions',
  'My23Actions',
  'My24Actions',
  'My25Actions',
  'My26Actions',
  'My27Actions',
  'My28Actions',
  'My29Actions',
  'My30Actions',
  'My31Actions',
];

export const CompanyMonth = [
  'Avg1Actions',
  'Avg2Actions',
  'Avg3Actions',
  'Avg4Actions',
  'Avg5Actions',
  'Avg6Actions',
  'Avg7Actions',
  'Avg8Actions',
  'Avg9Actions',
  'Avg10Actions',
  'Avg11Actions',
  'Avg12Actions',
  'Avg13Actions',
  'Avg14Actions',
  'Avg15Actions',
  'Avg16Actions',
  'Avg17Actions',
  'Avg18Actions',
  'Avg19Actions',
  'Avg20Actions',
  'Avg21Actions',
  'Avg22Actions',
  'Avg23Actions',
  'Avg24Actions',
  'Avg25Actions',
  'Avg26Actions',
  'Avg27Actions',
  'Avg28Actions',
  'Avg29Actions',
  'Avg30Actions',
  'Avg31Actions',
];

export const IndividualMonths = [
  'MyJanActions',
  'MyFebActions',
  'MyMarActions',
  'MyAprActions',
  'MyMayActions',
  'MyJunActions',
  'MyJulActions',
  'MyAugActions',
  'MySepActions',
  'MyOctActions',
  'MyNovActions',
  'MyDecActions',
];

export const AllMonths = [
  'AvgJanActions',
  'AvgFebActions',
  'AvgMarActions',
  'AvgAprActions',
  'AvgMayActions',
  'AvgJunActions',
  'AvgJulActions',
  'AvgAugActions',
  'AvgSepActions',
  'AvgOctActions',
  'AvgNovActions',
  'AvgDecActions',
];

export const monthNames = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];
